### ISSUE TITLE
Missing DDPM

### ISSUE THREAD

**Issue by blaisedelattre** [hukkai/liresnet#2]
Hello, thank you, for this nice repo ! 
I tried to launch training with DDPM, but the file {data_root}/c{num_classes}_ddpm.npz' is missing for CIFAR10. Can you provide a way to download it please?

**Comment by hukkai** [comment]
@blaisedelattre Sorry for the late reply. You can download `c10_ddpm.npz` here: https://drive.google.com/file/d/11beyNYWny24c_dHJPZT0MiKBwZ2Uz6N-/view?usp=sharing 
Will update other files soon.

**Comment by blaisedelattre** [comment]
Thank you !

**Comment by thib-s** [comment]
Hi, sorry for re-opening this issue, but I am also interested in having access to this file. But the link is dead, could you update it, please?
