### ISSUE TITLE
Code for ViT experiments

### ISSUE THREAD

**Issue by RohanMenon** [hukkai/liresnet#3]
Hello, thank you, for this nice repo!

In your paper, you mention that you perform experiments with ViT architecture(Table 7). Is it possible to share those scripts?

Cheers!

**Comment by hukkai** [comment]
Hi @RohanMenon Sorry for the late reply. We may release the code for the ViT results sometimes later, maybe after the NIPS submission deadline since we have some urgent work to do now.

**Comment by RohanMenon** [comment]
Thank you for your reply! I completely understand 🙂

**Comment by RohanMenon** [comment]
Above comments are self-explanatory
