### ISSUE TITLE
Missing DDPM

### ISSUE THREAD

**Issue by thib-s** [hukkai/liresnet#4]
Hi, sorry for re-opening issue #2, but I am also interested in having access to the missing file `{data_root}/c{num_classes}_ddpm.npz`. Unfortunately, the link you provided in your response to issue #2 seems dead, I would be glad if you could update it. Many thanks!

**Comment by hukkai** [comment]
@thib-s Sorry for the missing file. It was deleted by mistake. We will re-generate it and update it soon and will let you know.

**Comment by hukkai** [comment]
@thib-s 

CIFAR10: https://drive.google.com/file/d/1xMIvEyzw3J1CXY5MbCmnvEuT2OxUVYVL/view?usp=share_link
CIFAR100: https://drive.google.com/file/d/1Mi4EAzy-bF-SW3tkKdWfgSnoI8ETfK1E/view?usp=share_link

**Comment by thib-s** [comment]
Perfect, thank you very much 🙏

**Comment by hukkai** [comment]
If you have any issues, feel free to re-open it.
